//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Calculadora {
	
	protected System.Web.UI.HtmlControls.HtmlForm form1;
	
	protected System.Web.UI.WebControls.TextBox txtresultado;
	
	protected System.Web.UI.WebControls.Button btnborrar;
	
	protected System.Web.UI.WebControls.Button btnsiete;
	
	protected System.Web.UI.WebControls.Button btnocho;
	
	protected System.Web.UI.WebControls.Button btnnueve;
	
	protected System.Web.UI.WebControls.Button btndividir;
	
	protected System.Web.UI.WebControls.Button btncuatro;
	
	protected System.Web.UI.WebControls.Button btncinco;
	
	protected System.Web.UI.WebControls.Button btnseis;
	
	protected System.Web.UI.WebControls.Button btnmultiplicar;
	
	protected System.Web.UI.WebControls.Button btnraizcuadrada;
	
	protected System.Web.UI.WebControls.Button btnuno;
	
	protected System.Web.UI.WebControls.Button btndos;
	
	protected System.Web.UI.WebControls.Button btntres;
	
	protected System.Web.UI.WebControls.Button btnrestar;
	
	protected System.Web.UI.WebControls.Button btnexponencial;
	
	protected System.Web.UI.WebControls.Button btncero;
	
	protected System.Web.UI.WebControls.Button btncoma;
	
	protected System.Web.UI.WebControls.Button btnsumar;
	
	protected System.Web.UI.WebControls.Button btnigual;
}
